### ISSUE TITLE
Sinclair ACs are supported!

### ISSUE THREAD

**Issue by grmelacz** [eibenp/homebridge-gree-airconditioner#10]
**Is your feature request related to a problem? Please describe:**
As the Gree A/C models are very similar to Sinclair (well, probably it is just a different sticker from the same factory), I thought Sinclair might be supported as well. Even the mobile app is apparently the same as Gree's and the model name displayed there looks familiar too - `GR_AC_10001_09_<serial>`.

**Describe the solution you'd like:**
In fact, no modification to the plugin is needed. It just works as is! Enter the MAC of each unit as the README instructions and the unit is shown in the Home app once Homebridge is restarted.

All plugin available features are supported on the Sinclair SIH-13BITW indoor unit. No warnings or errors are triggered.

![IMG_0012](https://github.com/eibenp/homebridge-gree-airconditioner/assets/41264018/3b710cbf-7bb3-4f32-ab14-a1475e26613f)
![IMG_0013](https://github.com/eibenp/homebridge-gree-airconditioner/assets/41264018/3debabae-24e1-455f-b729-363a543d534d)
![IMG_0014](https://github.com/eibenp/homebridge-gree-airconditioner/assets/41264018/36a6654a-4e62-4c6a-9f0d-225bbcf9f124)

**Additional context:**
Config excerpt:

```
        {
            "mac": "502cc6xxxxxx",
            "name": "Living Room AC",
            "model": "Sinclair SIH-13BITW",
            "speedSteps": 5,
            "statusUpdateInterval": 10,
            "sensorOffset": 42,
            "minimumTargetTemperature": 16,
            "maximumTargetTemperature": 30,
            "xFanEnabled": false,
            "temperatureSensor": "disabled"
        }
```
Please note the `sensorOffset` has been set to match the smart radiator thermostat.

**Comment by eibenp** [comment]
Thank you for this useful information
