### ISSUE TITLE
Support for Gree Pular

### ISSUE THREAD

**Issue by mateuszmulak** [eibenp/homebridge-gree-airconditioner#11]
Does anyone have experience with the Gree Pular model? Does this plugin work for this model?

**Comment by mateuszmulak** [comment]
or another question - do you know how to check if given model has GREE GRJ532-J14 Wifi Modul or GREE CS532AE Wifi Modul that are not supported?

**Comment by eibenp** [comment]
> Does anyone have experience with the Gree Pular model? Does this plugin work for this model?

I have no information about GREE Pular model but you can safely try it

**Comment by mateuszmulak** [comment]
I’m asking because I haven’t bought the AC yet and want to know what models are supported

**Comment by eibenp** [comment]
> or another question - do you know how to check if given model has GREE GRJ532-J14 Wifi Modul or GREE CS532AE Wifi Modul that are not supported?



> or another question - do you know how to check if given model has GREE GRJ532-J14 Wifi Modul or GREE CS532AE Wifi Modul that are not supported?

These two unsupported Wifi modules are additional modules sold separately. They can be used to add Wifi functionality to GREE AC units without Wifi capabilities. If your unit has factory default Wifi functionality it should have a different modul.

**Comment by mateuszmulak** [comment]
Great! Thanks! Would you be able to share some Gree AC that you know that are supported for sure?

**Comment by eibenp** [comment]
GREE Pulse 3.2kW GWH12AGB-K6DNA1A/I works fine.
I have just received a comment about Sinclair SIH-13BITW which also works fine (this is a GREE clone device).
Unfortunately GREE does not support this project and any new device may have a new unsupported firmware. So I can not guarantee any device compatibility.
Maybe some users can recommend you additional devices. (I do not have information about the installations. Homebridge license prohibits data collection from the users.)

**Comment by mateuszmulak** [comment]
Thanks a lot!

**Comment by eibenp** [comment]
@mateuszmulak You can choose any GREE AC. New network encryption protocol is implemented and published in **v2.1.0** Currently there are no known unsupported GREE AC units
