### ISSUE TITLE
Node.js v22 support

### ISSUE THREAD

**Issue by tothbe** [eibenp/homebridge-gree-airconditioner#18]
Could you please add v22 support for node.js as it is the latest approved version and it generates warning that this plugin does not support it. Thanks.

**Comment by eibenp** [comment]
I will add it soon

**Comment by eibenp** [comment]
Hi @tothbe 
Node.js v22 is supported in version 2.1.3 and later.

**Comment by tothbe** [comment]
Thanks man, you are just amazing.
