### ISSUE TITLE
Incorrect minimum temperature range.

### ISSUE THREAD

**Issue by Przemekmac1** [eibenp/homebridge-gree-airconditioner#21]
Minimum temperature at plugin is 16C but AC's work from 13. 

Its expected to be able setup min temp. of 13C

{
    "name": "GREE Air Conditioner",
    "scanInterval": 60,
    "devices": [
        {
            "mac": "****",
            "name": "Hangar 1A",
            "speedSteps": 5,
            "statusUpdateInterval": 10,
            "sensorOffset": 40,
            "minimumTargetTemperature": 16,
            "maximumTargetTemperature": 30,
            "xFanEnabled": false,
            "temperatureSensor": "disabled",
            "overrideDefaultVerticalSwing": 0,
            "defaultVerticalSwing": 0,
            "encryptionVersion": 0
        },
        {
            "mac": "****",
            "name": "Hangar 1B",
            "speedSteps": 5,
            "statusUpdateInterval": 10,
            "sensorOffset": 40,
            "minimumTargetTemperature": 16,
            "maximumTargetTemperature": 30,
            "xFanEnabled": false,
            "temperatureSensor": "disabled",
            "overrideDefaultVerticalSwing": 0,
            "defaultVerticalSwing": 0,
            "encryptionVersion": 0
        }
    ],
    "_bridge": {
        "username": "",
        "port": 47870
    },
    "platform": "GREEAirConditioner"
}

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by eibenp** [comment]
Hi @Przemekmac1 
I need your help because I have never seen a GREE AC which works below 16 °C. Even the official GREE+ mobile app does not support temperatures outside of the 16-30 °C range.
I will be happy to extend this range but I need some information about your AC unit. Better said about the network communication of your AC unit. Please create some debug logs. Set your AC unit to the minimum temperature and wait until status updates appear in the log. Then set your unit to the maximum temperature and wait for the next status log entries. I need also the values of the minimum and maximum temperatures which I should search in the logs. It would help me if you create some additional tests with different temperatures outside of the 16-30 °C range and tell me which values are included in the logs. Finally please attach the logs to this issue.
Thank You!

**Comment by Przemekmac1** [comment]
Wifi firmware at the unit is 1.23, 
![IMG_8694](https://github.com/user-attachments/assets/3520ef1c-ea22-43f9-bcea-0921703d6784)

**Comment by eibenp** [comment]
Thank You!
Please turn on debug mode in homebridge and send me debug level logs about your units. The attached log contains only information level messages not debug ones. You can turn on debug mode on the settings page in homebridge UI.

**Comment by Przemekmac1** [comment]
[homebridge-gree-ac.log.txt](https://github.com/user-attachments/files/17836945/homebridge-gree-ac.log.txt)

here it is

**Comment by eibenp** [comment]
Thank You!
If I understand well then 8 °C is the minimum and 30 °C is the maximum in heating mode on your device, Am I right?
What are the limits in cooling mode?

**Comment by Przemekmac1** [comment]
Yes - heat mode is 8C-30C, cooling mode is 16C - 30C.
We use it mainly for heating :)

**Comment by eibenp** [comment]
Would you be so kind to set your AC unit to Fahrenheit display mode and collect some more debug logs?
I need primarily the lines containing "handleMessage - Package -> {...}" and "Device status -> {...}"
I need these lines and information of the target temperature (in Fahrenheit) which was set when the log entry was written.
I need information at least about 46°F, 47°F, 50°F, 59°F, 60°F, 61°F but it would be nice if I could get all values between 46°F and 62°F (Please mark every log entry to let me know the temperature which should be logged by the actual entry. Log entries do not contain Fahrenheit values so I can't decide the real value without additional information.)
Thank You!

**Comment by Przemekmac1** [comment]
Sure, attached.
[homebridge-gree-ac.log.txt](https://github.com/user-attachments/files/17851677/homebridge-gree-ac.log.txt)

Its Hangar 1B

**Comment by Przemekmac1** [comment]
Sorry,I was too fast. Here its new log. I changed heating target every minute (Hangar 1B).
21:49 46F
21:50 47F
21:51 50F
21:52 59F
21:53 60F
21:54 61F

I hope it logged correctly. 
[Uploading homebridge-gree-ac.log (1).txt…]()

**Comment by Przemekmac1** [comment]
[homebridge-gree-ac.log (1).txt](https://github.com/user-attachments/files/17851909/homebridge-gree-ac.log.1.txt)

**Comment by Przemekmac1** [comment]
I can see also that if I select temp below 16C homekit shows me always 25C.

**Comment by eibenp** [comment]
Yes, it's normal in the current version. Network communication does not use exact temperature values. It uses codes. If the plugin receives an unknown code then it replaces the unknow code with the default 25°C value.
I am already working on a solution.

**Comment by Przemekmac1** [comment]
Super, if you need something let me know :)

**Comment by Przemekmac1** [comment]
It works great, thanks! :)

**Comment by eibenp** [comment]
You are welcome!
